"""Module contracts. Each module exposes a Protocol so we can mock cleanly in tests."""

from __future__ import annotations

from collections.abc import Callable
from typing import Any, Protocol, runtime_checkable

from cuttix.models.alert import Alert
from cuttix.models.host import Host
from cuttix.models.scan_result import ScanResult


@runtime_checkable
class Scanner(Protocol):
    def scan(
        self, network: str | None = None, timeout: float = 2.0, retries: int = 2
    ) -> list[Host]: ...
    def get_known_hosts(self) -> dict[str, Host]: ...
    @property
    def interface(self) -> str: ...


@runtime_checkable
class ARPControl(Protocol):
    def cut_access(self, target_ip: str, auto_restore_minutes: int = 0) -> None: ...
    def restore_access(self, target_ip: str) -> None: ...
    def restore_all(self) -> None: ...
    def get_spoofed(self) -> dict[str, Any]: ...
    def is_spoofed(self, target_ip: str) -> bool: ...


@runtime_checkable
class PortScanner(Protocol):
    def scan_host(
        self, target_ip: str, ports: list[int] | None = None, technique: str = "connect"
    ) -> ScanResult: ...
    def scan_top_ports(self, target_ip: str, top_n: int = 100) -> ScanResult: ...


@runtime_checkable
class PacketCapture(Protocol):
    def start(self, bpf_filter: str = "", callback: Callable | None = None) -> None: ...
    def stop(self) -> None: ...
    def is_running(self) -> bool: ...
    def get_stats(self) -> dict[str, int]: ...


@runtime_checkable
class IDS(Protocol):
    def start(self) -> None: ...
    def stop(self) -> None: ...
    def get_alerts(self, since: float | None = None) -> list[Alert]: ...
    def get_whitelist(self) -> set[str]: ...
    def add_to_whitelist(self, mac: str) -> None: ...


@runtime_checkable
class ReportGenerator(Protocol):
    def generate(self, fmt: str = "json", output_path: str | None = None) -> str: ...
    def get_supported_formats(self) -> list[str]: ...
